### ISSUE TITLE
How to set the default task ?

### ISSUE THREAD

**Issue by mickaelandrieu** [BrunoMoreno/CmderRemaster#1]
Hi,

thank you for your work.

I use babun through Cmder to have multi tab feature. I have set my babun task but I don't see any option to set this task as the default task launched when I run Cmder.

Any hint ? Maybe directly on the XML configuration file ? 

Regards,

**Comment by msenturk** [comment]
Settings->Startup->Specified named task->Pick babun task

**Comment by mickaelandrieu** [comment]
Thank you (but now I work on ubuntu ^^)

closed.
